### ISSUE TITLE
Fixing the Top-Nav

### ISSUE THREAD

**Issue by MarcoMorawec** [ScottWatson19288/splurty#2]
Your top navigation bar doesn't look clean anymore. A top nav is used only for the most important items and adding links to other pages or image hover effects into it is generally a confusing user experience.

I suggest you remove the extra link and the image hover effect from the top nav and - if you want to keep those items - add the link into the footer and the hover over effect on a separate page.

Here's what I see:

![screen shot 2015-05-22 at 4 34 35 pm](https://cloud.githubusercontent.com/assets/1474717/7779287/22ca14ee-00a1-11e5-86d8-bca06db1fdc0.png)

**Comment by ScottWatson19288** [comment]
yes, I see thanks for the feedback, I will work on these 2 issues

**Comment by MarcoMorawec** [comment]
Awesome! Keep up the good work @ScottWatson19288

**Comment by ScottWatson19288** [comment]
Ok I think I have those 2 issues worked out.
